/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lwq_ndk_basic_MyJNI */

#ifndef _Included_com_lwq_ndk_basic_MyJNI
#define _Included_com_lwq_ndk_basic_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lwq_ndk_basic_MyJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lwq_ndk_1basic_MyJNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
